# This is a basic workflow to help you get started with Actions

name: Regression_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "regression_test"
  regression_test:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, linux ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Donwload regression test 
        shell: bash
        env:
          REGRESSION_TEST_TOKEN: ${{ secrets.regression_test_token }}
        run: |
          if [ -f regression_test/regression_test.py ] 
          then
            echo "Regression test has exist"
          else
            git clone "https://xuanweishan:$REGRESSION_TEST_TOKEN@github.com/xuanweishan/gamer_regression_test.git" regression_test
          fi

      - name: Set up environment
        run: |
          module list
          module load intel openmpi hdf5 fftw cuda valgrind gsl
          module list
    
      - name: Run regression test
        run: |
          cd regression_test
          python3 regression_test.py --machine spock_intel
